nome = str(input('Digite o seu nome completo: ')).strip()
print("Analisando o seu nome...")
print('Seu nome em maiusculas e {}'.format(nome.upper()))
print('Seu nome em minusculas e {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print("Seu primeiro nome trm {} letras".format(nome.find(" ")))  
print(nome.capitalize())
divide = nome.split()
print('Seu primeiro nome e {} e ele tem {} letras'.format(divide[0], len(divide[0])))